# Generated by Django 2.2 on 2019-12-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191217_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Location',
            new_name='location',
        ),
    ]
